### ISSUE TITLE
Guest auth fails when specifying an incorrect password for smb3

### ISSUE THREAD

**Issue by pfsen** [jfjallid/go-shareenum#3]
In SMB3 when a password is provided for a server that requires signing, auth fails even though the server supports server authentication:

```bash
user@box:~/tools$ ./go-shareenum -host 10.10.11.175 -enum -user 'someone' -pass 'asdsd'
2023/07/06 13:55:16 [Notice] [-] Signing is required
2023/07/06 13:55:16 [Notice] [+] Login successful
2023/07/06 13:55:17 [Error] read tcp 10.10.14.17:60768->10.10.11.175:445: read: connection reset by peer
panic: close of closed channel

goroutine 1 [running]:
github.com/jfjallid/go-smb/smb.(*outstandingRequests).shutdown(0x14?, {0x0?, 0x0})
	/home/user/projects/go/pkg/mod/github.com/jfjallid/go-smb@v0.2.1/smb/connection.go:275 +0xf0
github.com/jfjallid/go-smb/smb.(*Connection).Close(0xc000114370)
	/home/user/projects/go/pkg/mod/github.com/jfjallid/go-smb@v0.2.1/smb/session.go:1511 +0xe8
main.main()
	/home/user/git/go-shareenum/main.go:262 +0xfc4
```

**Comment by jfjallid** [comment]
Fixed in commit 948f327ee299058cc730552b2adc996dd4e59f59
